name: Typescript Testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - .vscode/**
      - LICENSE
  pull_request:
    paths-ignore:
      - '*.md'
      - .vscode/**
      - LICENSE

jobs:
  tests:
    runs-on: docker-runner
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Prune Docker
        run: docker system prune -af
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install node_modules
        run: yarn
      - name: Build Package
        run: yarn build
      - name: ESLint
        run: yarn lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn test:cov --colors
          debug: false
